#
# Currently we have two build stages:
#  - build (for traditional build and test or first stage build)
#  - test (for test stages, using build artefacts from a build stage)
stages:
  - build
  - test

variables:
  BASE_CONFIG: "--disable-docs"
  MAIN_SOFTMMU_TARGETS: "aarch64-softmmu,mips64-softmmu,ppc64-softmmu,riscv64-softmmu,s390x-softmmu,x86_64-softmmu"

include:
  - local: '/.gitlab-ci.d/edk2.yml'
  - local: '/.gitlab-ci.d/opensbi.yml'

# We assume GitLab has it's own caching set up for RPM/APT repositories so we
# just take care of avocado assets here.
cache:
  paths:
    - $HOME/avocado/data/cache

.update_apt_template: &before_script_apt
 before_script:
  - apt-get update -qq
  - apt-get install -y -qq git gcc libglib2.0-dev libpixman-1-dev make
        genisoimage
  - JOBS=$(expr $(nproc) + 1)

.update_dnf_template: &before_script_dnf
 before_script:
  - dnf update -y
  - dnf install -y bzip2 diffutils gcc git genisoimage findutils glib2-devel
        make python3 perl-podlators perl-Test-Harness pixman-devel zlib-devel
  - JOBS=$(expr $(nproc) + 1)

.post_acceptance_template: &post_acceptance
  after_script:
    - python3 -c 'import json; r = json.load(open("tests/results/latest/results.json")); [print(t["logfile"]) for t in r["tests"] if t["status"] not in ("PASS", "SKIP")]' | xargs cat
      - du -chs $HOME/avocado/data/cache

build:system-ubuntu-main:
 image: ubuntu:19.10
 stage: build
 <<: *before_script_apt
 script:
 - apt-get install -y -qq libgtk-3-dev libvte-dev nettle-dev libcacard-dev
      libusb-dev libvde-dev libspice-protocol-dev libgl1-mesa-dev libvdeplug-dev
 - mkdir build
 - cd build
 - ../configure ${BASE_CONFIG} --enable-werror --target-list="${MAIN_SOFTMMU_TARGETS}"
 - make -j"$JOBS"
 artifacts:
   paths:
     - build

check:system-ubuntu-main:
 image: ubuntu:19.10
 stage: test
 dependencies:
 - build:system-ubuntu-main
 <<: *before_script_apt
 script:
 - cd build
 - make check

acceptance:system-ubuntu-main:
 image: ubuntu:19.10
 stage: test
 dependencies:
 - build:system-ubuntu-main
 <<: *before_script_apt
 script:
 - DEBIAN_FRONTEND=noninteractive apt-get install -y -qq
    python3-pil python3-pip python3-numpy python3-opencv python3-venv
    rpm2cpio tesseract-ocr tesseract-ocr-eng
 - cd build
 - make check-acceptance
 <<: *post_acceptance

build:system-debian-alt:
 image: debian:buster-slim
 stage: build
 <<: *before_script_apt
 script:
 - apt-get install -y -qq libgtk-3-dev libvte-dev nettle-dev libcacard-dev
      libusb-dev libvde-dev libspice-protocol-dev libgl1-mesa-dev libvdeplug-dev
 - mkdir build
 - cd build
 - ../configure ${BASE_CONFIG} --enable-werror --disable-user
     --target-list-exclude="${MAIN_SOFTMMU_TARGETS}"
 - make -j"$JOBS"
 artifacts:
   paths:
     - build

check:system-debian-alt:
 image: debian:buster-slim
 stage: test
 dependencies:
 - build:system-debian-alt
 <<: *before_script_apt
 script:
 - cd build
 - make check

acceptance:system-debian-alt:
 image: debian:buster-slim
 stage: test
 dependencies:
 - build:system-debian-alt
 <<: *before_script_apt
 script:
 - DEBIAN_FRONTEND=noninteractive apt-get install -y -qq
    python3-pil python3-pip python3-numpy python3-opencv python3-venv
    rpm2cpio tesseract-ocr tesseract-ocr-eng
 - cd build
 - make check-acceptance
 <<: *post_acceptance

build:system-fedora-misc:
 image: fedora:latest
 stage: build
 <<: *before_script_dnf
 script:
 - yum install -y SDL2-devel libgcrypt-devel brlapi-devel libaio-devel
       libfdt-devel lzo-devel librdmacm-devel libibverbs-devel libibumad-devel
       libzstd-devel
 - mkdir build
 - cd build
 - ../configure --enable-werror --target-list="tricore-softmmu unicore32-softmmu
      microblaze-softmmu mips-softmmu riscv32-softmmu s390x-softmmu sh4-softmmu
      sparc64-softmmu x86_64-softmmu xtensa-softmmu nios2-softmmu or1k-softmmu"
 - make -j"$JOBS"
 artifacts:
   paths:
     - build

check:system-fedora-misc:
 image: fedora:latest
 stage: test
 dependencies:
 - build:system-fedora-misc
 <<: *before_script_dnf
 script:
 - cd build
 - make check

acceptance:system-fedora-misc:
 image: fedora:latest
 stage: test
 dependencies:
 - build:system-fedora-misc
 <<: *before_script_dnf
 script:
 - yum install -y python3-pillow python3-pip python3-numpy python3-opencv
       python3-virtualenv tesseract tesseract-langpack-eng
 - cd build
 - make check-acceptance
 <<: *post_acceptance

build:system-fedora-misc-disabled:
 image: fedora:latest
 stage: build
 <<: *before_script_dnf
 script:
 - mkdir build
 - cd build
 - ../configure --enable-werror --disable-rdma --disable-slirp --disable-curl
      --disable-capstone --disable-live-block-migration --disable-glusterfs
      --disable-replication --disable-coroutine-pool --disable-smartcard
      --disable-guest-agent --disable-curses --disable-libxml2 --disable-tpm
      --disable-qom-cast-debug --disable-spice --disable-vhost-vsock
      --disable-vhost-net --disable-vhost-crypto --disable-vhost-user
      --target-list="i386-softmmu ppc64-softmmu mips64-softmmu i386-linux-user"
 - make -j"$JOBS"
 artifacts:
   paths:
     - build

qtest:system-fedora-misc-disabled:
 image: fedora:latest
 stage: test
 dependencies:
 - build:system-fedora-misc-disabled
 <<: *before_script_dnf
 script:
 - cd build
 - make check-qtest SPEED=slow

build-tcg-disabled:
 image: centos:8
 stage: build
 <<: *before_script_dnf
 script:
 - dnf install -y clang gtk3-devel libusbx-devel libgcrypt-devel
 - mkdir build
 - cd build
 - ../configure --cc=clang --enable-werror --disable-tcg --audio-drv-list=""
 - make -j"$JOBS"
 - make check-unit
 - make check-qapi-schema
 - cd tests/qemu-iotests/
 - ./check -raw 001 002 003 004 005 008 009 010 011 012 021 025 032 033 048
            052 063 077 086 101 104 106 113 148 150 151 152 157 159 160 163
            170 171 183 184 192 194 197 208 215 221 222 226 227 236 253 277
 - ./check -qcow2 028 051 056 057 058 065 067 068 082 085 091 095 096 102 122
            124 132 139 142 144 145 151 152 155 157 165 194 196 197 200 202
            208 209 215 216 218 222 227 234 246 247 248 250 254 255 257 258
            260 261 262 263 264 270 272 273 277 279

build-user:
 stage: build
 <<: *before_script_apt
 script:
 - mkdir build
 - cd build
 - ../configure --enable-werror --disable-system --disable-guest-agent
               --disable-capstone --disable-slirp --disable-fdt
 - make -j"$JOBS"
 - make run-tcg-tests-i386-linux-user run-tcg-tests-x86_64-linux-user

build-clang:
 image: fedora:latest
 stage: build
 <<: *before_script_dnf
 script:
 - yum install -y clang SDL2-devel libattr-devel libcap-ng-devel xfsprogs-devel
       libiscsi-devel libnfs-devel libseccomp-devel gnutls-devel librbd-devel
 - mkdir build
 - cd build
 - ../configure --cc=clang --cxx=clang++ --enable-werror
      --target-list="alpha-softmmu arm-softmmu m68k-softmmu mips64-softmmu
                     ppc-softmmu s390x-softmmu x86_64-softmmu arm-linux-user"
 - make -j"$JOBS"
 - make -j"$JOBS" check

build-tci:
 image: centos:8
 stage: build
 <<: *before_script_dnf
 script:
 - TARGETS="aarch64 alpha arm hppa m68k microblaze moxie ppc64 s390x x86_64"
 - mkdir build
 - cd build
 - ../configure --enable-tcg-interpreter
      --target-list="$(for tg in $TARGETS; do echo -n ${tg}'-softmmu '; done)"
 - make -j"$JOBS"
 - make run-tcg-tests-x86_64-softmmu
 - make tests/qtest/boot-serial-test tests/qtest/cdrom-test tests/qtest/pxe-test
 - for tg in $TARGETS ; do
     export QTEST_QEMU_BINARY="${tg}-softmmu/qemu-system-${tg}" ;
     ./tests/qtest/boot-serial-test || exit 1 ;
     ./tests/qtest/cdrom-test || exit 1 ;
   done
 - QTEST_QEMU_BINARY="x86_64-softmmu/qemu-system-x86_64" ./tests/qtest/pxe-test
 - QTEST_QEMU_BINARY="s390x-softmmu/qemu-system-s390x"
   ./tests/qtest/pxe-test -m slow
