# GitHub actions - Create QEMU installers for Windows

# The action is restricted to https://github.com/qemu/qemu.
# That avoids an unnecessary waste of resources when each fork
# runs the action, too.

name: Cross build for Windows

on: [push]

jobs:
  build:
    strategy:
      matrix:
        arch: [32, 64]
    if: github.repository == 'qemu/qemu'
    runs-on: [ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2
    - name: Build QEMU installer (${{ matrix.arch }} bit)
      run: .github/workflows/build.sh ${{ matrix.arch }}
    - uses: actions/upload-artifact@v1
      with:
        name: QEMU Installer Windows ${{ matrix.arch }} bit
        path: dist
